### ISSUE TITLE
Improper typeof check

### ISSUE THREAD

**Issue by Zeludon** [RonenNess/adder#1]
https://github.com/RonenNess/adder/blob/master/src/index.js#L14

``` js
if (typeof window !== undefined) {
    window.AdderScript = adder;
};
```

should be `typeof window !== "undefined"`

this is causing the module to not work under node for me.

**Comment by RonenNess** [comment]
Hi thanks for the report! Its a mistake in the file that require everything for node.js, I will fix it as soon as I'll get home from work. 
Meanwhile so you can start using and experiment with it you can require() the index used for testing (its the same but with internal stuff required), called "index_tests.js". Then you'll have 'global.AdderScript.Adder' object which is the same object you'd get if the original require worked. 

Sorry about that!

**Comment by RonenNess** [comment]
Fixed, thanks :)
There was also a confusion with which file to require in Node.js, that's also fixed.

If you want a quick test you can update Adder Script and run the following code:

```

var AdderScript = require("adder-script")

// init Adder environment (connect output to console)
AdderScript.init({
    outputFunc: function(text) {console.log("output from script: " + text);},
});

// create a simple script and compile it
compiledCode = AdderScript.compile('print("Hello World!")');

// spawn a program and execute it
// the result will be an alert with the text "Hello World!".
var program = AdderScript.newProgram(compiledCode);
program.execute();
```

It should work properly.
Thanks again!
