### ISSUE TITLE
Performance numbers in Readme

### ISSUE THREAD

**Issue by katywings** [RonenNess/adder#2]
Hey hey ^^

Very nice thing you've created here! One question though:
- Is the compilation step in the numbers of the performance tests included or is it only the execution of the build?
  (My backend will probably be Elixir and i am wondering if I could speed up the execution by caching the build step ^^)

Thx for your feedback in advance and toodaloo ;)

**Comment by RonenNess** [comment]
Hi Katy, thanks!

The performance tests do not include the compile time, only execution. 

In addition its important to mention that after the first time a program executes some internal caching is made, so next runs are faster - this factor also affected the performance tests (for example mathematical expressions and some built-in functions may be cached).

So best practice for performance is:
1. Pre-compile everything you can. 
2. If you need to run the same program multiple times its best to use the same program instance and not respawn a new program every time (so you can enjoy internal caching).

I added the comments above to the Readme file.

May I close this ticket or there's anything else you'd like to know on this subject?
Thanks!

**Comment by katywings** [comment]
Hey Ronen

Ty for the detailled answer, that absolutely fine. I will try it out and see how it works in my env ;)

Toodaloo
Katja
